FROM node:14.15.0 as build

RUN mkdir -p /var/app
WORKDIR /var/app

COPY package*.json ./

RUN npm ci
COPY . .
ARG DW_API_URL
ARG DW_SENTRY
ARG DW_RELEASE
ARG DW_NETWORK
RUN DW_API_URL=$DW_API_URL DW_SENTRY=$DW_SENTRY DW_RELEASE=$DW_RELEASE DW_NETWORK=$DW_NETWORK npm run build



FROM nginx:alpine as main

WORKDIR /app

COPY --from=build /var/app ./

RUN ls
COPY ./nginx.conf /etc/nginx/nginx.conf

EXPOSE 8080