FROM node:14.18.3 as build

RUN mkdir -p /var/app
WORKDIR /var/app

COPY package*.json ./
COPY .npmrc ./
RUN npm ci
COPY . .

RUN DW_API_URL=$DW_API_URL DW_SENTRY=$DW_SENTRY DW_RELEASE=$DW_RELEASE npm run build
COPY . .



FROM node:alpine as main

COPY --from=build /var/app ./
RUN npm install -g http-server
COPY . .


EXPOSE 8080

CMD [ "http-server", "dist" ]