---
- name: Deploy Application
  hosts: all
  become: yes

  tasks:
  
  - name: Ping servers
    ping:

  - name: Pull new image of frontend app
    community.docker.docker_image:
      name: deipworld/dev-wallet-frontend
      source: pull
  
  - name: docker-compose UP
    docker_compose:
      build: no
      definition: docker-compose.yaml
    register: output


      