name: Deploy to Amazon ECS

on:
  push:
    branches:
      - development

env:
  DW_API_URL: ${{ secrets.DW_API_URL }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  IMAGE_TAG: ${{ github.sha }}
  DW_RELEASE: ${{ github.sha }}
  DW_SENTRY: ${{ secrets.SENTRY_DSN }} 



jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v2
      with:
        node-version: '14.18.3'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: $AWS_ACCESS_KEY_ID
        aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
        aws-region: eu-central-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build -t $ECR_REGISTRY/wallet-frontend:$IMAGE_TAG --build-arg DW_API_URL=$DW_API_URL --build-arg DW_SENTRY=$DW_SENTRY --build-arg DW_RELEASE=$DW_RELEASE -f Dockerfile.dev .
        docker push $ECR_REGISTRY/wallet-frontend:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/wallet-frontend:$IMAGE_TAG"

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ecs-task.json
        container-name: frontend-task
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: frontend_service
        cluster: dev-wallet
        wait-for-service-stability: false
