name: Deployment
on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-18.04

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        
      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./src/dist
          remote_path: /var/www/wallet/
          remote_host: ec2-3-124-116-65.eu-central-1.compute.amazonaws.com
          remote_user: root
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"

