name: Deployment
on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        
      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          ls ${{ github.workspace }}/src

      # - name: Run Ansible playbook
      #   uses: dawidd6/action-ansible-playbook@v2.5.0
      #   with:
      #     playbook: deploy-playbook.yaml 
      #     directory: ./ansible
      #     key: ${{ secrets.SSH_PRIVATE_KEY }} 
      #     inventory: |
      #       [production_server]
      #       linux2 ansible_host=${{ secrets.ANSIBLE_HOST }}  ansible_user=ec2-user 



