name: Deployment
on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-18.04

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        
      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy App
        run: |
          aws s3 sync ./src/dist s3://$AWS_S3_BUCKET --delete --acl public-read
        env:
          AWS_S3_BUCKET: ${{secrets.AWS_S3_BUCKET}}

      # - name: Update CloudFront Destribution
      #   run: |
      #     aws cloudfront create-invalidation --distribution-id $DESTRIBUTION_ID --paths "/*"
      #   env:
      #     DESTRIBUTION_ID: ${{secrets.DESTRIBUTION}}

